import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "Cryptonova | Cybersecurity That Powers Confidence",
  description:
    "Cryptonova delivers cutting-edge cybersecurity solutions including ethical hacking, AI threat detection, and secure development. Protect your digital future with us.",
  keywords: [
    "Cybersecurity",
    "Ethical Hacking",
    "AI Threat Detection",
    "Security Audits",
    "Cryptonova",
    "Secure Development",
    "VAPT",
    "Cyber Awareness Training",
  ],
  openGraph: {
    title: "Cryptonova | Cybersecurity That Powers Confidence",
    description:
      "Protect your business with AI-driven security, ethical hacking, and proactive threat detection.",
    url: "https://cryptonova.in",
    siteName: "Cryptonova",
    images: [
      {
        url: "https://cryptonova.in/images/og-banner.jpg", // Replace with actual image
        width: 1200,
        height: 630,
        alt: "Cryptonova Cybersecurity Banner",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Cryptonova | Cybersecurity That Powers Confidence",
    description:
      "Cutting-edge protection with AI, ethical hacking, and secure development.",
    images: ["https://cryptonova.in/images/og-banner.jpg"], // Replace with actual image
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
       <Footer />
      </body>
    </html>
  );
}
